### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by tylerjnap** [ColorfullyMe/idol-client#1]
Hi,

```
npm install idol-client
```

doesn't seem to work.  Is this a bug or I am typing this incorrectly?

**Comment by kkartunov** [comment]
@tylernappy  It does for me. Have tried currently... Is your net up and working?
![image](https://cloud.githubusercontent.com/assets/5585002/7687026/eeb3b65c-fda2-11e4-9baf-0ed6a07d5d2b.png)

**Comment by kkartunov** [comment]
@tylernappy It looks you ware right... There was some issue with the npm published package. Do not know why. Anyway now it should work:

```
npm install idol-client
```
